### ISSUE TITLE
Modal Null Value error

### ISSUE THREAD

**Issue by danielruss** [episphere/quest#448]
useing Tony's test module:

```
[ERROR_EDIT] Validate Error Check Modal
|__|__|__|min=0 max=999 softedit=true modalif=value<70 modalvalue='Is this weight correct?'|
 
[HARD_EDIT!] Validate Hard Error Modal
|__|id=HARD_EDIT_1|
|__|id=HARD_EDIT_2|
```

Uncaught TypeError: Cannot set properties of null (setting 'innerText')
    at textboxinput (questionnaire.js:557:19)
    at HTMLInputElement.textBoxInput (questionnaire.js:422:3)
textboxinput @ questionnaire.js:557
textBoxInput @ questionnaire.js:422

**Comment by danielruss** [comment]
two issues: 
  1) the modal element id was wrong: should be softModalResponseBody
  2) There is a bootstrap 4/5 change with modal. In BS4 you use data-dismiss="modal"  to hide the modal in BS5 you use data-bs-dismiss="modal".  Because the PWA uses BS4 and Quest Dev tool uses BS5... add both.  Consider if we should be using Bootstrap so deeply in quest, even though I really like it.

PR coming soon

**Comment by danielruss** [comment]
to be fix when the spanish implementation is merged.  Keeping issue open until then.
